const STORAGE_KEY="long_weekend_trip_v1";
const options=[
{id:"hakone",name:"箱根",subtitle:"温泉と美術館で、移動を欲張らない",icon:"♨",tags:["温泉","美術館","近距離"],cost:{save:"約10万円",standard:"約16万円",reward:"約24万円"},travel:"東京から約1.5〜2時間",hotel:"箱根宮ノ下 明星館",hotelPrice:"2泊2名 55,600円表示",hotelUrl:"https://www.booking.com/hotel/jp/myojokan.html?aid=2438770&checkin=2026-11-21&checkout=2026-11-23&no_rooms=1&group_adults=2&selected_currency=JPY",transportUrl:"https://www.hakonenavi.jp/",scores:{scenery:4,food:4,onsen:5,art:5,relax:5,novelty:3,mobility:5},summary:"海外旅行直後でも疲れにくい本命。温泉、彫刻の森、芦ノ湖を詰め込みすぎず楽しむ。",itinerary:[["1日目","昼前に箱根湯本。蕎麦または豆腐料理→宮ノ下散策→温泉。"],["2日目","彫刻の森美術館→強羅ランチ→宿で休憩。夜は会席または外食。"],["3日目","芦ノ湖・元箱根を短く散策。混雑前に東京へ戻る。"]]},
{id:"kanazawa",name:"金沢",subtitle:"食と工芸を、街歩きの密度で楽しむ",icon:"工",tags:["海鮮","工芸","街歩き"],cost:{save:"約12万円",standard:"約18万円",reward:"約26万円"},travel:"東京から北陸新幹線で約2.5時間",hotel:"KOKO HOTEL Premier 金沢香林坊",hotelPrice:"2泊2名 96,000円表示",hotelUrl:"https://www.booking.com/hotel/jp/trusty-kanazawa-korinbo.html?aid=2438770&checkin=2026-11-21&checkout=2026-11-23&no_rooms=1&group_adults=2&selected_currency=JPY",transportUrl:"https://www.kanazawa-kankoukyoukai.or.jp/",scores:{scenery:4,food:5,onsen:2,art:5,relax:3,novelty:4,mobility:4},summary:"食を主役にするなら最強。近江町市場、茶屋街、21世紀美術館、工芸を徒歩とバスで回せる。",itinerary:[["1日目","昼に金沢着。近江町市場→主計町・ひがし茶屋街→寿司。"],["2日目","兼六園→21世紀美術館→工芸体験→加賀料理。"],["3日目","長町武家屋敷→甘味→早めの新幹線で帰宅。"]]},
{id:"setouchi",name:"高松・直島",subtitle:"島と現代アートで、非日常へ振り切る",icon:"島",tags:["島旅","現代アート","うどん"],cost:{save:"約13万円",standard:"約19万円",reward:"約25万円"},travel:"羽田から高松空港＋港・船移動",hotel:"Blue Nest Takamatsu",hotelPrice:"2泊2名 82,000円表示",hotelUrl:"https://www.booking.com/hotel/jp/blue-nest-takamatsu.html?aid=2438770&checkin=2026-11-21&checkout=2026-11-23&no_rooms=1&group_adults=2&selected_currency=JPY",transportUrl:"https://www.city.takamatsu.kagawa.jp/kanko_tannoshimu/index.html",scores:{scenery:5,food:4,onsen:2,art:5,relax:3,novelty:5,mobility:2},summary:"一番記憶に残るが、船と天候の影響あり。直島アート、高松のうどん、瀬戸内の景色を楽しむ。",itinerary:[["1日目","午前便で高松。うどん→栗林公園→港周辺で夕食。"],["2日目","朝の船で直島。美術館・家プロジェクトを予約枠に合わせて回る。"],["3日目","高松市内でうどんと買い物。午後便で帰京。"]]}
];
const prefs=[{id:"scenery",label:"景色"},{id:"food",label:"食"},{id:"onsen",label:"温泉"},{id:"art",label:"アート・文化"},{id:"relax",label:"ゆっくり"},{id:"novelty",label:"珍しい体験"},{id:"mobility",label:"移動の楽さ"}];
const defaultState={schedule:{start:"2026-11-21",end:"2026-11-23",budget:"standard"},active:0,locked:null,participants:[{id:crypto.randomUUID(),name:"みぶ",weights:{scenery:5,food:5,onsen:4,art:4,relax:3,novelty:5,mobility:3},ratings:{hakone:4,kanazawa:5,setouchi:5},veto:{},must:{}},{id:crypto.randomUUID(),name:"あづき",weights:Object.fromEntries(prefs.map(p=>[p.id,3])),ratings:{hakone:0,kanazawa:0,setouchi:0},veto:{},must:{}}]};
let state=load();
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function load(){try{return {...structuredClone(defaultState),...JSON.parse(localStorage.getItem(STORAGE_KEY)||"null")}}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderAll()}
function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
function days(){const a=new Date(state.schedule.start),b=new Date(state.schedule.end);return Math.max(1,Math.round((b-a)/86400000))}
function renderOptions(){const budget=state.schedule.budget;$("#destinationGrid").innerHTML=options.map((o,i)=>`<article class="destination-card"><div class="destination-visual"><div><small>OPTION 0${i+1}</small><br><strong>${o.icon} ${o.name}</strong></div></div><div class="destination-body"><h3>${o.subtitle}</h3><p>${o.summary}</p><div class="tag-row">${o.tags.map(t=>`<span class="tag">${t}</span>`).join("")}</div><div class="destination-meta"><div class="meta-box"><small>概算</small><strong>${o.cost[budget]}</strong></div><div class="meta-box"><small>移動</small><strong>${o.travel}</strong></div></div><div class="destination-actions"><button class="btn btn-outline detail-btn" data-id="${o.id}">旅程を見る</button><a class="btn btn-primary" href="#preferences">採点する</a></div></div></article>`).join("");$$('.detail-btn').forEach(b=>b.onclick=()=>openDetail(b.dataset.id))}
function openDetail(id){const o=options.find(x=>x.id===id);$("#dialogKicker").textContent=`${o.name} / SAMPLE PLAN`;$("#dialogTitle").textContent=o.subtitle;$("#dialogBody").innerHTML=`<p>${o.summary}</p><div class="timeline">${o.itinerary.map(x=>`<div class="timeline-item"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join("")}</div><div class="privacy-note"><strong>宿候補：</strong>${o.hotel}<br>${o.hotelPrice}</div>`;$("#detailDialog").showModal()}
function renderTabs(){$("#participantTabs").innerHTML=state.participants.map((p,i)=>`<button class="participant-tab ${i===state.active?'active':''}" data-i="${i}">${escapeHtml(p.name||`参加者${i+1}`)}</button>`).join("")+`<button class="participant-tab" id="addParticipant">＋ 友人</button>`;$$('[data-i]').forEach(b=>b.onclick=()=>{state.active=+b.dataset.i;save()});$("#addParticipant").onclick=()=>{state.participants.push({id:crypto.randomUUID(),name:`友人${state.participants.length-1}`,weights:Object.fromEntries(prefs.map(p=>[p.id,3])),ratings:Object.fromEntries(options.map(o=>[o.id,0])),veto:{},must:{}});state.active=state.participants.length-1;save()}}
function renderProfile(){const p=state.participants[state.active];$("#profileEditor").innerHTML=`<div class="profile-name-row"><input id="participantName" value="${escapeHtml(p.name)}" aria-label="名前"><button class="btn btn-outline" id="copyCode">回答コードをコピー</button></div><h4>何を重視する？ 1〜5</h4><div class="preference-grid">${prefs.map(x=>`<div class="preference-item"><label><span>${x.label}</span><output>${p.weights[x.id]}</output></label><input type="range" min="1" max="5" value="${p.weights[x.id]}" data-weight="${x.id}"></div>`).join("")}</div><div class="rating-table"><h4>各候補の気持ち</h4>${options.map(o=>`<div class="rating-row"><div class="rating-head"><strong>${o.name}</strong><div class="stars">${[1,2,3,4,5].map(n=>`<button class="star ${p.ratings[o.id]>=n?'on':''}" data-rate="${o.id}" data-n="${n}" aria-label="${n}点">★</button>`).join("")}</div></div><div class="musts"><label><input type="checkbox" data-must="${o.id}" ${p.must[o.id]?'checked':''}>絶対やりたい</label><label><input type="checkbox" data-veto="${o.id}" ${p.veto[o.id]?'checked':''}>これは避けたい</label></div></div>`).join("")}</div>`;
$("#participantName").onchange=e=>{p.name=e.target.value.trim()||p.name;save()};$$('[data-weight]').forEach(el=>el.oninput=e=>{p.weights[e.target.dataset.weight]=+e.target.value;e.target.previousElementSibling.querySelector('output').textContent=e.target.value;localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderDecision()});$$('[data-rate]').forEach(el=>el.onclick=()=>{p.ratings[el.dataset.rate]=+el.dataset.n;save()});$$('[data-must]').forEach(el=>el.onchange=()=>{p.must[el.dataset.must]=el.checked;if(el.checked)p.veto[el.dataset.must]=false;save()});$$('[data-veto]').forEach(el=>el.onchange=()=>{p.veto[el.dataset.veto]=el.checked;if(el.checked)p.must[el.dataset.veto]=false;save()});$("#copyCode").onclick=()=>copyCode(p)}
function score(option,p){const total=prefs.reduce((s,x)=>s+p.weights[x.id],0);const fit=prefs.reduce((s,x)=>s+option.scores[x.id]*p.weights[x.id],0)/total;const feeling=p.ratings[option.id]||0;return fit*.62+feeling*.38+(p.must[option.id]?.3:0)-(p.veto[option.id]?3:0)}
function results(){return options.map(o=>{const individual=state.participants.map(p=>score(o,p));const rated=state.participants.every(p=>(p.ratings[o.id]||0)>0);const veto=state.participants.some(p=>p.veto[o.id]);const avg=individual.reduce((a,b)=>a+b,0)/individual.length;const spread=Math.max(...individual)-Math.min(...individual);const final=avg-spread*.22;return {o,individual,rated,veto,avg,spread,final}}).sort((a,b)=>b.final-a.final)}
function renderDecision(){const r=results();$("#scoreboard").innerHTML=r.map(x=>`<div class="score-row"><strong>${x.o.name}</strong><div class="score-track"><div class="score-fill" style="width:${Math.max(0,Math.min(100,x.final/5*100))}%"></div></div><span>${x.final.toFixed(1)}</span></div>`).join("");const top=r[0],complete=r.every(x=>x.rated),agreement=complete&&!top.veto&&top.avg>=4&&top.spread<=1.15;$("#consensusStatus").innerHTML=!complete?`<div class="status-card warn"><strong>全候補の採点待ち</strong><br>全員が3候補すべてを1〜5点で採点すると判定します。</div>`:agreement?`<div class="status-card good"><strong>${top.o.name}で合意可能</strong><br>平均 ${top.avg.toFixed(1)}、意見差 ${top.spread.toFixed(1)}、拒否なし。</div>`:`<div class="status-card warn"><strong>まだ合意なし</strong><br>首位は${top.o.name}ですが、平均4.0以上・意見差1.15以内・拒否なしの条件を満たしていません。</div>`;const btn=$("#lockWinnerBtn");btn.disabled=!agreement;btn.textContent=state.locked?`${options.find(o=>o.id===state.locked)?.name}で確定済み`:'合意候補を確定';btn.onclick=()=>{state.locked=top.o.id;save();toast(`${top.o.name}を合意候補に確定しました`)};$("#summaryStatus").textContent=state.locked?`${options.find(o=>o.id===state.locked).name}で合意`:(agreement?`${top.o.name}が合意圏内`:'意見入力中')}
function renderBooking(){const el=$("#bookingPanel");if(!state.locked){el.innerHTML=`<div class="booking-locked"><h3>🔒 予約ゲートは未解放</h3><p>全員の採点と合意が揃うと、選ばれた候補の宿・交通リンクが表示されます。</p></div>`;return}const o=options.find(x=>x.id===state.locked);el.innerHTML=`<h3>${o.name}の予約準備</h3><p>${o.hotelPrice}は確認時点の参考表示です。外部画面で日付、人数、部屋、キャンセル条件、総額を必ず再確認してください。</p><div class="booking-options"><a class="booking-link" href="${o.hotelUrl}" target="_blank" rel="noreferrer"><strong>宿泊候補を確認 ↗</strong><small>${o.hotel} / Booking.com</small></a><a class="booking-link" href="${o.transportUrl}" target="_blank" rel="noreferrer"><strong>交通・現地情報を確認 ↗</strong><small>公式観光・交通サイト</small></a></div><div class="privacy-note"><strong>予約チェックリスト</strong><br>①氏名表記 ②総額 ③キャンセル期限 ④食事条件 ⑤交通の確保。全部一致してから確定してください。</div>`}
function copyCode(p){const payload={version:1,participant:p};const code='LW1.'+btoa(unescape(encodeURIComponent(JSON.stringify(payload))));navigator.clipboard.writeText(code).then(()=>toast('回答コードをコピーしました'))}
function importCode(){try{const raw=$("#importCode").value.trim();if(!raw.startsWith('LW1.'))throw new Error();const data=JSON.parse(decodeURIComponent(escape(atob(raw.slice(4)))));if(!data.participant?.id)throw new Error();const i=state.participants.findIndex(p=>p.id===data.participant.id);if(i>=0)state.participants[i]=data.participant;else state.participants.push(data.participant);save();$("#importCode").value='';toast('回答を取り込みました')}catch{toast('回答コードを読み取れませんでした')}}
function escapeHtml(s=''){return String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function renderAll(){$("#startDate").value=state.schedule.start;$("#endDate").value=state.schedule.end;$("#budgetMode").value=state.schedule.budget;$("#summaryDates").textContent=`${days()}泊${days()+1}日`;renderOptions();renderTabs();renderProfile();renderDecision();renderBooking()}
$("#saveScheduleBtn").onclick=()=>{const start=$("#startDate").value,end=$("#endDate").value;if(!start||!end||new Date(end)<=new Date(start)){toast('帰宅日は出発日より後にしてください');return}state.schedule={start,end,budget:$("#budgetMode").value};save();toast('日程を保存しました')};$("#budgetMode").onchange=()=>{state.schedule.budget=$("#budgetMode").value;save()};$("#importCodeBtn").onclick=importCode;$("#resetBtn").onclick=()=>{if(confirm('入力内容を初期化しますか？')){state=structuredClone(defaultState);save()}};$("#closeDialogBtn").onclick=()=>$("#detailDialog").close();$("#shareSiteBtn").onclick=async()=>{const data={title:document.title,text:'ロングウィークエンド旅行の候補を一緒に採点しよう',url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);toast('URLをコピーしました')}}catch{}};renderAll();